Updated indentation

diff --git a/backend-flask/bin/ddb/drop b/backend-flask/bin/ddb/drop
--- a/backend-flask/bin/ddb/drop
+++ b/backend-flask/bin/ddb/drop
@@ -1,19 +1,20 @@
-#!/usr/bin/env bash
+#! /usr/bin/bash
 
-if [ -z "#1" ]; then
-  echo "NO TABLE_NAME argument supplied eg. ./backend-flask/bin/ddb/drop cruddur-messages prod"
-  exit
+set -e # stop if it fails at any point
+
+if [ -z "$1" ]; then
+  echo "No TABLE_NAME argument supplied eg ./bin/ddb/drop cruddur-messages prod "
+  exit 1
 fi
-
 TABLE_NAME=$1
 
 if [ "$2" = "prod" ]; then
-  ENDPOINT_URL = ""
+  ENDPOINT_URL=""
 else
-    ENDPOINT_URL="--endpoint_url=http://localhost:8000"
+  ENDPOINT_URL="--endpoint-url=http://localhost:8000"
 fi
 
-echo "DELETING TABLE: $TABLE_NAME"
+echo "deleting table: $TABLE_NAME"
 
 aws dynamodb delete-table $ENDPOINT_URL \
---table_name  $TABLE_NAME\
+  --table-name $TABLE_NAME
